// This is an array of characters for forming the options during quiz
const characters = [
'Walter White',
'Jesse Pinkman',
'Skyler White',
'Walter White Jr.',
'Henry Schrader',
'Mike Ehrmantraut',
'Marie Schrader',
'Saul Goodman',
'Gustavo Fring',
'Hector Salamanca',
'Domingo Molina',
'Marco & Leonel Salamanca',
'Tuco Salamanca',
'Lydia Rodarte-Quayle',
'Todd Alquist',
'Jane Margolis',
'Skinny Pete',
'Brandon Mayhew',
'Huell Babineaux',
'Steven Gomez',
'Theodore Beneke',
'Gale Boetticher',
'Andrea Cantillo',
'Brock Cantillo',
'Carmen Molina',
'Gretchen Schwartz',
'Elliot Schwartz',
'Gonzo',
'Christian Ortgea',
'Mrs. Pinkman',
'Adam Pinkman',
'Jake Pinkman',
'No-Doze',
'Emilio Koyama',
'Dr. Delcavoli',
'Wendy S.',
'Bogdan Wolynetz',
'Ken',
'Holly White',
'George Merkert',
'Donald Margolis',
'Clovis',
'SAC Ramey',
'Victor',
'Tomás Cantillo',
'Francesca Liddy',
'Cynthia',
'Tortuga',
'Tim Roberts'
]